version: '3.8'
services:
    api:
        ports:
            - 5000:5000
        container_name: studentlist_api
        volumes:
            - ./simple_api/student_age.json:/data/student_age.json
        image: api.student_list.img
        networks:
           - studentlist_network

    webapp:
        ports:
            - 80:80
        container_name: studentlist_webapp
        environment:
          USERNAME: toto
          PASSWORD: python             
        volumes:
            - ./website/index.php:/var/www/html/index.php
        image: php:apache
        networks:
            - studentlist_network
        depends_on:
            - api
networks:
  studentlist_network:
    driver: bridge


